### ISSUE TITLE
Error with generated code and Dagger

### ISSUE THREAD

**Issue by szkodnik25** [tommus/ktx-prefs#1]
It seems like there is a problem with the order in which the annotation processors are launched for Dagger v2 and ktx-prefs. When I want to inject ktx-prefs generated class with Dagger v2 as a module doing clean build, the generated classes from ktx-prefs are not found in Dagger generated classes (even though they generated successfully and are present in kapt directory). 

After gradle file change, that forces synchronization, build goes just fine. But it's not clean build - generated ktx-prefs classes are present. After successfull build and clean - the "bugged" scenario is repeated.

**Comment by szkodnik25** [comment]
It's not related to ktx-prefs.

**Comment by tommus** [comment]
Agreed. I will add an example how to configure ktx-prefs with Dagger.

**Comment by tommus** [comment]
I have added an [example](https://github.com/tommus/ktx-prefs/tree/master/samples/kotlin-dagger) of using Dagger as a dependency injection tool.

For one who would like to use most recent Dagger version (it is 2.21 in a moment of writing this comment) there is a known issue related with Jetifier described in more details [here](https://github.com/google/dagger/issues/1245). 

Being said, it might be necessary to add newer version of Jetifier compiler to project classpath. Please do not hesitate to take a fast glance as it is already present in the project's `build.gradle` for `kotlin-dagger` sample purposes.
