### ISSUE TITLE
Incorrect first value from field's Flowable

### ISSUE THREAD

**Issue by wojKrz** [tommus/ktx-prefs#3]
After subscribing to field's Flowable, first item emitted is always default value, even if this field was set previously

Steps to reproduce

1. Save value in field
2. Dispose of stream related to this field, and subscribe again (i.e. by killing an app)
Result: First item emitted is default value instead of one set in step 1.

**Comment by tommus** [comment]
Thank you for your report.

This issue has been addressed within version [1.4.0](https://github.com/tommus/ktx-prefs/releases/tag/1.4.0).

It is already available in Maven Central.
